language: node_js

cache: yarn

notifications:
  email: false

node_js:
  - '9'
  - '8'

install:
  - yarn
  - yarn global add codecov

after_success:
  - nyc report --reporter=json && codecov -f coverage/*.json

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
