export const OBJECT_TYPE_METADATA_KEY = Symbol('OBJECT_TYPE_METADATA_KEY');
export const QUERY_METADATA_KEY = Symbol('QUERY_METADATA_KEY');
export const MUTATION_METADATA_KEY = Symbol('MUTATION_METADATA_KEY');
